/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package KonversiSuhu;

/**
 *
 * @author ASUS
 */
public class KonversiSuhu extends javax.swing.JFrame {
   
    /**
     * Creates new form KonversiSuhu
     */
    public KonversiSuhu() {
        initComponents();
        
        radio1.setVisible(false);
        radio2.setVisible(false);
        radio3.setVisible(false);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        judulLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        radio3 = new javax.swing.JRadioButton();
        radio2 = new javax.swing.JRadioButton();
        radio1 = new javax.swing.JRadioButton();
        actionLabel = new javax.swing.JLabel();
        suhuBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        konversiButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        inputTeks = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        hasilKonversi = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        resetButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        judulLabel.setFont(new java.awt.Font("Gill Sans MT", 0, 48)); // NOI18N
        judulLabel.setText("Konversi Suhu");

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setForeground(new java.awt.Color(153, 153, 153));

        buttonGroup1.add(radio3);
        radio3.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N

        buttonGroup1.add(radio2);
        radio2.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N

        buttonGroup1.add(radio1);
        radio1.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N

        actionLabel.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        actionLabel.setText("Menu Action :");

        suhuBox.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        suhuBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Selected Menu--", "Kelvin", "Celcius", "Fahrenheit", "Reamur" }));
        suhuBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suhuBoxActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        jLabel2.setText("Menu Pilih Suhu");

        konversiButton.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        konversiButton.setText("Konversi");
        konversiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                konversiButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(konversiButton)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(radio3)
                        .addComponent(suhuBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(actionLabel)
                        .addComponent(radio1)
                        .addComponent(radio2)))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(suhuBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(actionLabel)
                .addGap(32, 32, 32)
                .addComponent(radio1)
                .addGap(18, 18, 18)
                .addComponent(radio2)
                .addGap(18, 18, 18)
                .addComponent(radio3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(konversiButton)
                .addGap(40, 40, 40))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setForeground(new java.awt.Color(153, 153, 153));

        inputTeks.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        inputTeks.setText(" ");

        jLabel4.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        jLabel4.setText("Hasil Konversi :");

        hasilKonversi.setBackground(new java.awt.Color(102, 255, 102));
        hasilKonversi.setFont(new java.awt.Font("Gill Sans MT", 0, 24)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        jLabel1.setText("Input Suhu :");

        resetButton.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(inputTeks, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(hasilKonversi, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(resetButton)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputTeks, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(42, 42, 42)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(hasilKonversi, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(resetButton)
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(211, 211, 211)
                .addComponent(judulLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(judulLabel)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(139, 139, 139))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void hitung(){
      double reasult = 0;  
      double value = Double.valueOf(inputTeks.getText());
        
      if (suhuBox.getSelectedIndex() == 1){
          
          if (radio1.isSelected()) 
              reasult = (value - 273.15);
          if (radio2.isSelected()) 
              reasult = (value * 1.8 - 459.67);
          if (radio3.isSelected()) 
              reasult = ((value - 273.15)* 0.8);        
          
      }else if (suhuBox.getSelectedIndex() == 2){
          
          if (radio1.isSelected()) 
              reasult = (value + 273.15);
          if (radio2.isSelected()) 
              reasult = (value * 1.8 + 32);
          if (radio3.isSelected()) 
              reasult = (value * 0.8);  
      }else if (suhuBox.getSelectedIndex() == 3){
          
          if (radio1.isSelected()) 
              reasult = ((value + 459.67)/1.8);
          if (radio2.isSelected()) 
              reasult = ((value - 32)/1.8);
          if (radio3.isSelected()) 
              reasult = ((value -32)/2.25);  
      }
      else if (suhuBox.getSelectedIndex() == 4){
          
          if (radio1.isSelected()) 
              reasult = (value / 0.8 + 273.15);
          if (radio2.isSelected()) 
              reasult = (value / 0.8);
          if (radio3.isSelected()) 
              reasult = ((value - 7.5)* 24/7 + 32);  
      }
      hasilKonversi.setText("" + reasult);
    }
    
    private void suhuBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suhuBoxActionPerformed
        // TODO add your handling code here:
        if (suhuBox.getSelectedIndex()==1){
            radio1.setVisible(true);
            radio2.setVisible(true);
            radio3.setVisible(true);
            
            // munculkan teks
            radio1.setText("Kelvin ke Celcius");
            radio2.setText("Kelvin ke Fahrenheit");
            radio3.setText("Kelvin ke Reamur");
            
        } 
        else if (suhuBox.getSelectedIndex()==2) {
            radio1.setVisible(true);
            radio2.setVisible(true);
            radio3.setVisible(true);
            
            // munculkan teks
            radio1.setText("Celcius ke Kelvin ");
            radio2.setText("Celcius ke Fahrenheit");
            radio3.setText("Celcius ke Reamur");
        }
        else if (suhuBox.getSelectedIndex()==3) {
            radio1.setVisible(true);
            radio2.setVisible(true);
            radio3.setVisible(true);
            
            // munculkan teks
            radio1.setText("Fahrenheit ke Kelvin ");
            radio2.setText("Fahrenheit ke Celcius");
            radio3.setText("Fahrenheit ke Reamur");
        }
        else if (suhuBox.getSelectedIndex()==4) {
            radio1.setVisible(true);
            radio2.setVisible(true);
            radio3.setVisible(true);
            
            // munculkan teks
            radio1.setText("Reamur ke Kelvin ");
            radio2.setText("Reamur ke Celcius");
            radio3.setText("Reamur ke Fahrenheit");
        }
       
    }//GEN-LAST:event_suhuBoxActionPerformed

    private void konversiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_konversiButtonActionPerformed
        // TODO add your handling code here:
        hitung();
    }//GEN-LAST:event_konversiButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        // TODO add your handling code here:
        inputTeks.setText("");
        hasilKonversi.setText("");
        inputTeks.requestFocus();
        
    }//GEN-LAST:event_resetButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KonversiSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KonversiSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KonversiSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KonversiSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KonversiSuhu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel actionLabel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel hasilKonversi;
    private javax.swing.JTextField inputTeks;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel judulLabel;
    private javax.swing.JButton konversiButton;
    private javax.swing.JRadioButton radio1;
    private javax.swing.JRadioButton radio2;
    private javax.swing.JRadioButton radio3;
    private javax.swing.JButton resetButton;
    private javax.swing.JComboBox<String> suhuBox;
    // End of variables declaration//GEN-END:variables
}
