/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PenampilGambar;

import java.awt.CardLayout;
/**
 *
 * @author ASUS
 */
public class PenampilGambar extends javax.swing.JFrame {
    
  void penampilIMG(){
      
      if (pilihGambar.getSelectedIndex() == 1){
        CardLayout cl = (CardLayout)(panelGambar.getLayout());
        cl.show(panelGambar,"0");
        }else if (pilihGambar.getSelectedIndex() == 2){
            CardLayout cl = (CardLayout)(panelGambar.getLayout());
            cl.show(panelGambar,"1");
        }else if (pilihGambar.getSelectedIndex() == 3){
              CardLayout cl = (CardLayout)(panelGambar.getLayout());
              cl.show(panelGambar,"2");
        }else if (pilihGambar.getSelectedIndex() == 0){
              CardLayout cl = (CardLayout)(panelGambar.getLayout());
              cl.show(panelGambar,"3");
  }
  }
    public PenampilGambar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pilihGambar = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        exitBTM = new javax.swing.JButton();
        panelGambar = new javax.swing.JPanel();
        imgAyam1 = new javax.swing.JLabel();
        imgNasi = new javax.swing.JLabel();
        imgMie = new javax.swing.JLabel();
        imgAyam = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pilihGambar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "~Pilih Menu~", "Nasi Goreng", "Mie Goreng", "Ayam Bakar" }));
        pilihGambar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihGambarActionPerformed(evt);
            }
        });

        jLabel1.setText("Pilih Menu :");

        exitBTM.setText("Exit");
        exitBTM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBTMActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(jLabel1)
                .addGap(150, 150, 150)
                .addComponent(pilihGambar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exitBTM)
                .addGap(146, 146, 146))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pilihGambar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(exitBTM))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        panelGambar.setLayout(new java.awt.CardLayout());
        panelGambar.add(imgAyam1, "3");

        imgNasi.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Downloads\\nasi goreng 400jt.jpeg")); // NOI18N
        panelGambar.add(imgNasi, "0");

        imgMie.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Downloads\\mie goreng.jpg")); // NOI18N
        panelGambar.add(imgMie, "1");

        imgAyam.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Downloads\\Ayam bakar.jpg")); // NOI18N
        panelGambar.add(imgAyam, "2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelGambar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelGambar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pilihGambarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihGambarActionPerformed
        penampilIMG();
    }//GEN-LAST:event_pilihGambarActionPerformed

    private void exitBTMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBTMActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitBTMActionPerformed

    
    
    
   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PenampilGambar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PenampilGambar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PenampilGambar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PenampilGambar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PenampilGambar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exitBTM;
    private javax.swing.JLabel imgAyam;
    private javax.swing.JLabel imgAyam1;
    private javax.swing.JLabel imgMie;
    private javax.swing.JLabel imgNasi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelGambar;
    private javax.swing.JComboBox<String> pilihGambar;
    // End of variables declaration//GEN-END:variables
}
